### ISSUE TITLE
Line following code

### ISSUE THREAD

**Issue by kylestach** [KyleStach1678/cmp-arduino-1678#2]
Create the bare minimum code necessary for following lines. This does not need any fancy algorithms, but it needs to be consistent.

**Comment by LyraSolomon** [comment]
The thick line code worked on the thin lines, but it oscillated, so I tweaked it a bit and it works really well, except for a few random times when it just ignores any lines. Find. Fix. The code is still on Windows #1 because the internet died just as I was trying to push.

**Comment by LyraSolomon** [comment]
Code now on github.
